### ISSUE TITLE
how to run VIO with euroc?

### ISSUE THREAD

**Issue by holyly** [VIS4ROB-lab/multi_robot_coordination#4] opened 2021-03-19 13:05 UTC
Hi, I am very interested in this project...  How should I proceed if I want to run only master-clients VIO  with the dataset of Euroc  (GPS values are not used as input)? I look forward to your answer!!

**Comment by lucaBartolomei** [comment] 2021-03-19 16:18
Hi, 
thanks a lot for the interest in the project. 

If you are interested in the pose-graph optimization, you can have a look at the [corresponding repository](https://github.com/VIS4ROB-lab/pose_graph_backend). In particular, if you want to test it with the EuRoC dataset, you can follow [these instructions](https://github.com/VIS4ROB-lab/pose_graph_backend#1-euroc-dataset). At the moment it requires a GPS input (i.e. the Leica measurements in the case of EuRoC), as it was designed in that way. However, you can disable the GPS measurements from the parameter configuration from the launch files.

I will close this issue anyway, since it is not related to this repo. If you need additional help, feel free to open a new issue in the pose-graph optimization repository. Hope this helps.

**Closed as completed by lucaBartolomei** 2021-03-19 16:18 UTC

**Comment by holyly** [comment] 2021-03-20 03:41
Thanks!!!!!
